### ISSUE TITLE
What's the most simplified way to use this?

### ISSUE THREAD

**Issue by FxllenCode** [grilme99/Rodentify#1]
Hi @grilme99!

First off, the idea behind this is really cool! I think it is very smart to make sure requests are coming from a Roblox server.

I have a couple of questions regarding this module. (Disclaimer: New to Node.js, mainly use JS for the web.)

* I'm looking to one-time have this run, not set this up to automatically check, just so I can run it. (I'm running some security testing on my game.)
* I've read through the source and see which endpoint your using to do this, I've sent you a DM on the devforum regarding that as I don't want to disclose some things publicly.  
* What is the npm for the crypto module? I've tried searching for it but cannot find it.

Thanks!

**Comment by grilme99** [comment]
> I'm looking to one-time have this run, not set this up to automatically check, just so I can run it. (I'm running some security testing on my game.)

Can you elaborate? You can just pass in the place ID and job ID of the server you're trying to test it on.

> What is the npm for the crypto module? I've tried searching for it but cannot find it.

[Crypto](https://nodejs.org/api/crypto.html) comes packaged with Node and provides lots of useful cryptographic functions.

**Comment by FxllenCode** [comment]
> Can you elaborate? You can just pass in the place ID and job ID of the server you're trying to test it on.

My bad for the missing clarification, I was just looking to use the endpoint one time, although I see my mistake now. 



> [Crypto](https://nodejs.org/api/crypto.html) comes packaged with Node and provides lots of useful cryptographic functions.

Turns out I had my node installed wrong, thanks!

**Comment by FxllenCode** [comment]
I'm still having issues with the crypto module...


![k76zBhcebb](https://user-images.githubusercontent.com/40151425/109427194-3af85600-79bf-11eb-902e-35183ea20dc2.png)

Here is my code for reference, it is no different than what you have but the crypto module errors:

![k6kUtdQjZp](https://user-images.githubusercontent.com/40151425/109427212-4ea3bc80-79bf-11eb-9e80-166e1f5f9f6d.png)

Thanks so much for your help!
