### ISSUE TITLE
No joinScriptUrl | Initial request failed

### ISSUE THREAD

**Issue by UnknownKachal** [grilme99/Rodentify#2]
![unknown](https://user-images.githubusercontent.com/68708434/111862390-0cebad80-8990-11eb-8b1c-8d90be80b728.png)
![unknown (1)](https://user-images.githubusercontent.com/68708434/111862400-1bd26000-8990-11eb-99ca-3f4d55f751fb.png)
![Annotation (1)](https://user-images.githubusercontent.com/68708434/111862412-2e4c9980-8990-11eb-8b66-466e3f75f91d.png)
Having issue with No joinScriptUrl and Initial request failed

```js
import rodentify from "rodentify";
rodentify.SetCookie(config.API_KEYS.ROBLOX);

export default async function getSevers(placeId, refPageId) {
    return new Promise(async (resolve, reject) => {
        const alive = await rodentify.GetServerData(placeId, refPageId)
        console.log(alive)
    })
}
```

```js
    return new Promise(async (resolve, reject) => {
        const alive = await rodentify.GetServerData(123456789, '4136c54c-07e6-11eb-adc1-0242ac120002')
        console.log(alive)
    })
 ```

**Comment by grilme99** [comment]
Have you read the [Limitations](https://github.com/grilme99/Rodentify#limitations) section of the README? Make sure that this method actually works with the place you're testing on.

**Comment by UnknownKachal** [comment]
Yep, I have read it, and followed every step, but it seems like I'm getting No joinScriptUrl. and my game has no restrictions and its free to play.
