### ISSUE TITLE
GetServerInfo is incorrectly capitalized

### ISSUE THREAD

**Issue by 6ixfalls** [grilme99/Rodentify#5]
After beginning to test this module on my Windows computer, I moved the code to a VPS to test it out on a live server. However, I kept encountering this error:
`Error: Cannot find module './GetServerInfo'`
After some troubleshooting, I was able to track down the issue.
In index.ts, GetServerInfo is required with a capital G. However, the file name is a lowercase g. This caused Linux/Debian machines to not be able to find the module.

**Comment by grilme99** [comment]
Fixed by #6.
